package:
  name:
  version:

source:
  path:
    ../

build:
  number: 0
  noarch: python
  script: pip install .

requirements:
  host:
    - pip
    - python
  run:
    - python

about:
  license: BSD
  license_file: LICENSE
  summary:
